# Configuración compatible con la versión actual de Nixpacks
providers = ["java"] 

# Versión corregida sin error de parsing
[build]
provider = "java"  # Proveedor principal
include = [
  "backend/*",
  "script_bbdd/script_vendix_bbdd.sql"
]

[build.environment]
JAVA_VERSION = "23"
PORT = "8080"
# Configuración MySQL
SPRING_DATASOURCE_URL = "jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true"
SPRING_DATASOURCE_USERNAME = "${MYSQLUSER}"
SPRING_DATASOURCE_PASSWORD = "${MYSQLPASSWORD}"

[build.buildCommand]
cmd = "cd backend && ./mvnw clean package -DskipTests -B --no-transfer-progress"

[build.startCommand]
cmd = "cd backend && java -jar target/*.jar"

[deploy]
setupCommand = """
  echo "Esperando a que MySQL esté listo..."
  sleep 15
  mysql -h ${MYSQLHOST} -P ${MYSQLPORT} -u ${MYSQLUSER} -p${MYSQLPASSWORD} ${MYSQLDATABASE} < script_bbdd/script_vendix_bbdd.sql
"""