[build]
include = [
  "backend/*",
  "script_bbdd/script_vendix_bbdd.sql"  # Incluye tu script SQL
]

[build.environment]
JAVA_VERSION = "23"  # o tu versión de Java
PORT = "8080"
SPRING_DATASOURCE_URL = "${RAILWAY_MYSQL_URL}"  # Variable automática para MySQL
SPRING_DATASOURCE_USERNAME = "${MYSQLUSER}"
SPRING_DATASOURCE_PASSWORD = "${MYSQLPASSWORD}"
SPRING_DATASOURCE_DRIVER_CLASS_NAME = "com.mysql.cj.jdbc.Driver"

[build.buildCommand]
cmd = "cd backend && ./mvnw clean package -DskipTests"  # Para Maven
# cmd = "cd backend && ./gradlew build -x test"  # Para Gradle

[build.startCommand]
cmd = "cd backend && java -jar target/*.jar"  # Para Maven
# cmd = "cd backend && java -jar build/libs/*.jar"  # Para Gradle

# Configuración para ejecutar script MySQL
[deploy]
setupCommand = "sleep 10 && mysql -h ${MYSQLHOST} -P ${MYSQLPORT} -u ${MYSQLUSER} -p${MYSQLPASSWORD} ${MYSQLDATABASE} < script_bbdd/script_vendix_bbdd.sql"