providers = ["java"]

[phases.setup]
nixPkgs = ["openjdk21", "mysql", "maven"]

[phases.build]
cmds = [
  "cd backend && ./mvnw dependency:purge-local-repository",
  "cd backend && ./mvnw clean install -DskipTests -B --fail-never",
  "cd backend && ./mvnw clean package -DskipTests -B"
]

[start]
cmd = "cd backend && java -jar target/*.jar"

[env]
JAVA_VERSION = "23"
PORT = "8080"
SPRING_DATASOURCE_URL = "jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true"
SPRING_DATASOURCE_USERNAME = "${MYSQLUSER}"
SPRING_DATASOURCE_PASSWORD = "${MYSQLPASSWORD}"

[deploy]
setupCommand = """
  echo "Esperando a que MySQL esté listo..."
  sleep 15
  mysql -h ${MYSQLHOST} -P ${MYSQLPORT} -u ${MYSQLUSER} -p${MYSQLPASSWORD} ${MYSQLDATABASE} < script_bbdd/script_vendix_bbdd.sql
"""
