[providers]
java = true
node = false  # Desactiva si no usas Node.js
python = false # Desactiva si no usas Python

[build]
provider = "java"  # Especifica el proveedor principal
include = [
  "backend/*",
  "script_bbdd/script_vendix_bbdd.sql"
]

[build.environment]
JAVA_VERSION = "23"
PORT = "8080"
# Configuración para MySQL
SPRING_DATASOURCE_URL = "jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}?useSSL=false&allowPublicKeyRetrieval=true"
SPRING_DATASOURCE_USERNAME = "${MYSQLUSER}"
SPRING_DATASOURCE_PASSWORD = "${MYSQLPASSWORD}"

[build.buildCommand]
cmd = "cd backend && ./mvnw clean package -DskipTests"

[build.startCommand]
cmd = "cd backend && java -jar target/*.jar"

[deploy]
setupCommand = """
  echo "Waiting for MySQL to be ready..."
  sleep 15
  mysql -h ${MYSQLHOST} -P ${MYSQLPORT} -u ${MYSQLUSER} -p${MYSQLPASSWORD} ${MYSQLDATABASE} < script_bbdd/script_vendix_bbdd.sql
"""